### ISSUE TITLE
Epic 7

### ISSUE THREAD

**Issue by PhatDave** [PhatDave/musicTribesPI#10]
- [ ] S7-1 Kao Member, kada pristupim TRIBE stranici, vidim sve playliste unutar Tribea
  i mogu im pristupiti
- [ ] S7-2 Kao Member, kada pristupim PLAYLIST stranici, vidim podatke o playlisti
- [ ] S7-3 Kao Member, kada pristupim PLAYLIST stranici, mogu dodati novu pjesmu u
  playlistu
- [ ] S7-4 Kao Anyone, kada pristupim PLAYLIST stranici, vidim podatke o pjesmama u
  playlisti i mogu poslušati bilo koju pjesmu u popisu pjesama
- [ ] S7-5 Kao Member, kada pristupim PLAYLIST stranici, mogu lajkati i unlikeati bilo koju
  pjesmu iz popisa i vidim za svaku pjesmu broj likeova
- [ ] S7-6 Kao Member, kada pristupim PLAYLIST stranici, mogu vidjeti koliko pojedina
  pjesma ima komentara te mogu čitati te komentare
- [ ] S7-7 Kao Member, kada pristupim PLAYLIST stranici, mogu komentirati svaku pjesmu u
  popisu pjesama
- [ ] S7-8 Kao User ili Anon, kada pristupim PLAYLIST stranici, mogu vidjeti komentare
  na pjesme ali ne mogu komentirati
- [ ] S7-9 Kao User ili Anon, kada pristupim PLAYLIST stranici, mogu vidjeti broj
  lajkova za pjesmu, ali ne mogu lajkati
