### ISSUE TITLE
Epic 1

### ISSUE THREAD

**Issue by PhatDave** [PhatDave/musicTribesPI#4]
- [ ] S1-1 Kao SuperAdmin, kada pristupim ADMIN_DASH stranici, trebam moći
  uređivati korisnike i postaviti im Admin privilegije
- [ ] S1-2 Kao Admin, kada pristupim ADMIN_DASH stranici, trebam moći
  uređivati korisnike i postaviti im Admin privilegije
- [ ] S1-3 Kao Admin, kada pristupim ADMIN_DASH stranici, trebam moći uređivati podatke
  o svim Tribeovima
