### ISSUE TITLE
Epic 2

### ISSUE THREAD

**Issue by PhatDave** [PhatDave/musicTribesPI#5]
- [ ] S2-1 Kao Anon, kada pristupim HOMEPAGE stranici, mogu registrirati novi korisnički
  račun, nakon čega me sustav redirecta nazad na HOMEPAGE
- [ ] S2-2 Kao Anon, kada pristupim HOMEPAGE stranici, mogu se prijaviti u aplikaciju,
  nakon čega me sustav redirect nazad na HOMEPAGE
- [ ] S2-3 Kao User, iz bilo kojeg dijela aplikacije, mogu pristupiti EDIT_USER stranici
  i urediti svoje korisničke podatke
- [ ] S2-4 Kao User, kada pristupim EDIT_USER stranici, mogu postaviti svoj logo
  (avatar)
