### ISSUE TITLE
Epic 3

### ISSUE THREAD

**Issue by PhatDave** [PhatDave/musicTribesPI#6]
- [ ] S3-1 Kao User, kada pristupim HOMEPAGE stranici, mogu kreirati novi Tribe
- [ ] S3-2 Kao User, kada pristupim HOMEPAGE stranici, mogu vidjeti postojeće Tribeove
- [ ] S3-3 Kao User, kada pristupim HOMEPAGE stranici, na popisu Tribeova vidim Tribeove
  razdvojene po tome jesam li Chieftain Tribea, jesam li Member, te ukoliko ne
  pripadam tom Tribeu
- [ ] S3-4 Kao User, kada pristupim HOMEPAGE stranici, mogu se priključiti Tribeu čiji
  nisam Member
- [ ] S3-5 Kao User, kada pristupim HOMEPAGE stranici, mogu pristupiti TRIBE stranici za
  bilo koji Tribe
