### ISSUE TITLE
Epic 4

### ISSUE THREAD

**Issue by PhatDave** [PhatDave/musicTribesPI#7]
- [ ] S4-1 Kao Chieftain, kada pristupim TRIBE stranici svog Tribea, mogu kreirati i
  brisati playliste
- [ ] S4-2 Kao Chieftain, kada pristupim TRIBE stranici, mogu uređivati
  naziv i opis svake playliste
- [ ] S4-4 Kao Chieftain, kada pristupim TRIBE stranici, mogu izbaciti
  Membera iz Tribea
