### ISSUE TITLE
Epic 6

### ISSUE THREAD

**Issue by PhatDave** [PhatDave/musicTribesPI#9]
- [ ] S6-1 Kao Member, kada pristupim TRIBE stranici, vidim popis poruka u Chatboxu
  Tribea koje su pisali Memberi Tribea
- [ ] S6-2 Kao Member, kada pristupim TRIBE stranici, mogu ostaviti poruku u Chatboxu
- [ ] S6-3 Kao Anyone, kada pristupim TRIBE stranici, poruke napisane u Chatboxu na toj
  TRIBE stranici vidim samo unutar te TRIBE stranice
- [ ] S6-4 Kao Chieftain, kada pristupim TRIBE stranici, mogu brisati poruke
  svih Membera iz Chatboxa mog Tribea
- [ ] S6-5 Kao Member, User ili Anon, kada pristupim TRIBE stranici, ne vidim opcije za brisanje poruka
  u Chatboxu i ne mogu ih moderirati
- [ ] S6-6 Kao Member ili User, kada pristupim TRIBE stranici, ne mogu brisati poruke u
  Chatboxu čak niti ako sam Chieftain nekog drugog Tribea
- [ ] S6-7 Kao Chieftain, kada pristupim TRIBE stranici,
  za sve moje poruke u Chatboxu vidljivo je da ih je napisao Chieftain Tribea.
